# Generated by Django 6.0 on 2026-07-22 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_order_inventory_reserved_and_more'),
        ('products', '0005_product_product_price_positive_and_more'),
        ('reviews', '0004_alter_review_options_review_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_valid'),
        ),
    ]
