# Generated by Django 6.0 on 2026-07-22 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialOffer', '0002_alter_specialoffer_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='badgeColor',
            field=models.CharField(default='bg-emerald-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='special_offers/'),
        ),
    ]
