# Generated by Django 6.0 on 2026-07-22 07:11

import django.core.validators
from django.db import migrations, models


def release_legacy_cart_reservations(apps, schema_editor):
    """Older code deducted inventory while an item merely sat in a cart."""
    CartItem = apps.get_model("cart", "CartItem")
    Product = apps.get_model("products", "Product")
    for item in CartItem.objects.all().iterator():
        Product.objects.filter(pk=item.product_id).update(stock=models.F("stock") + item.quantity)


def reserve_legacy_cart_inventory(apps, schema_editor):
    CartItem = apps.get_model("cart", "CartItem")
    Product = apps.get_model("products", "Product")
    for item in CartItem.objects.all().iterator():
        Product.objects.filter(pk=item.product_id).update(stock=models.F("stock") - item.quantity)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(release_legacy_cart_reservations, reserve_legacy_cart_inventory),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
