# Generated by Django 6.0 on 2026-07-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_updated_at_alter_cartitem_quantity_and_more'),
        ('products', '0005_product_product_price_positive_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_quantity_positive'),
        ),
    ]
